import numpy as np
import argparse
import time
import cv2
import os
import csv
from csv import writer
import random

bgpixels = np.zeros((19200,2),dtype=int)
bgpixelindex=0
done=['T']

ap = argparse.ArgumentParser()
ap.add_argument("-dir","--dir",type=str,
                default=os.path.sep.join(["C:/Hansel/MasterPool/"]),
                help="path to input image")
ap.add_argument("-c","--iter",type=int,default=40,
                help="# of GrabCut iterations (larger,slower)")
args = vars(ap.parse_args())
csvpath = args['dir']+"TdrMixPool_labels.csv"

for y in range(0,217):
    chosen=random.choice(os.listdir(args["dir"]+"Pool/"))
    with open(csvpath,newline='') as csvfile:
            DataInfo=np.zeros(8)
            csvReader = csv.reader(csvfile)
            Datas=list(csvReader)
            csvfile.close()
            for q in range(0,len(Datas)):
                if(Datas[q][0]==chosen):
                    for r in range(1,8):
                        if(r!=3):
                            DataInfo[r]=Datas[q][r]
    while((chosen.endswith(".jpg")==False)or(chosen.startswith("Back")==True)
          or((str(chosen) in done)==True)or(str(DataInfo[3])=="zero")
          or(chosen.startswith("basah")==True)or(chosen.startswith("bekas")==True)
          or(chosen.startswith("bottle")==True)or(chosen.startswith("glass")==True)
          or(chosen.startswith("hp")==True)or(chosen.startswith("kontras")==True)
          or(chosen.startswith("rokok")==True)or(chosen.startswith("Grass")==True)
          or(chosen.startswith("Aspal")==True)):
        chosen=random.choice(os.listdir(args["dir"]+"Pool/"))
        with open(csvpath,newline='') as csvfile:
            DataInfo=np.zeros(8)
            csvReader = csv.reader(csvfile)
            Datas=list(csvReader)
            csvfile.close()
            for q in range(0,len(Datas)):
                if(Datas[q][0]==chosen):
                    for r in range(1,8):
                        if(r!=3):
                            DataInfo[r]=Datas[q][r]
        
##    print(chosen)
    done.append(str(chosen))   

    image = cv2.imread(args["dir"]+"Pool/"+str(chosen))
##    cv2.imwrite(args['dir']+"trial/"+"Asli"+str(chosen),image)
    mask = np.zeros(image.shape[:2], dtype="uint8")

    #ambil info bounding box dari file csv...
    items = []
    Datas=np.zeros(1)

    #setelah tau mana gambar yg diAugmentasi, langsung tulis...
    with open(csvpath,'a',newline='') as csvobj:
        writer_object = writer(csvobj)
        Newlinew=["B3ack"+str(chosen),DataInfo[1],DataInfo[2],"tidur",DataInfo[4],DataInfo[5],DataInfo[6],DataInfo[7]] 
        writer_object.writerow(Newlinew)
        csvobj.close()
        
    bbox = (int(DataInfo[4]),int(DataInfo[5]),int(abs(DataInfo[4]-DataInfo[6])),int(abs(DataInfo[5]-DataInfo[7])))
##    print("xmin:"+str(DataInfo[4])+"; ymin:"+str(DataInfo[5])+"; xmax:"+str(DataInfo[6])+"ymax:"+str(DataInfo[7]))
    
    fgModel = np.zeros((1,65), dtype="float")
    bgModel = np.zeros((1,65), dtype="float")

    start=time.time()
    (mask, bgModel, fgModel) = cv2.grabCut(image, mask, bbox, bgModel,
            fgModel, iterCount=args["iter"], mode=cv2.GC_INIT_WITH_RECT)
    end = time.time()
##    print("[INFO] applying GrabCut took {:.2f} seconds".format(end - start))

    values = (
            ("Definite Background", cv2.GC_BGD),
            ("Probable Background", cv2.GC_PR_BGD),
            ("Definite Foreground", cv2.GC_FGD),
            ("Probable Foreground", cv2.GC_PR_FGD),
    )

    for (name, value) in values:
            # construct a mask that for the current value
##            print("[INFO] showing mask for '{}'".format(name))
            valueMask = (mask == value).astype("uint8") * 255
            # display the mask so we can visualize it
##            cv2.imshow(name, valueMask)
##            cv2.waitKey(0)

    outputMask = np.where((mask == cv2.GC_BGD) | (mask == cv2.GC_PR_BGD),
            0, 1)
    # scale the mask from the range [0, 1] to [0, 255]
    outputMask = (outputMask * 255).astype("uint8")
    # apply a bitwise AND to the image using our mask generated by
    # GrabCut to generate our final output image
    output = cv2.bitwise_and(image, image, mask=outputMask)

    dimensions=output.shape
    bgpixelindex=0
    for j in range(0,dimensions[0]):
        for i in range(0,dimensions[1]):
            (b,g,r)=output[j,i]
            #apakah keabu - abuan ?
            if (r==0&g==0&b==0):
                bgpixels[bgpixelindex][0]=int(j)
                bgpixels[bgpixelindex][1]=int(i)
                bgpixelindex+=1

    #convert to hsv biar lebih transisi warna fusionnya nyambung
    hsv = cv2.cvtColor(output, cv2.COLOR_BGR2HSV)
    for p in range(0,len(bgpixels)):
        #random abu apa warna ?
        if(random.random()>0.5): #ya, warna
            if(random.random()>0.5):
                h = random.uniform(250,360)
            else:
                h = random.uniform(0,60)
            h = (h/360)*179
            s = random.uniform(200,255)
            v = random.uniform(0,255)
        else:
            h = random.uniform(250,360)
            s = random.uniform(0,20)
            v = random.uniform(0,255)
        
        hsv[bgpixels[p][0],bgpixels[p][1]]=(h,s,v) #b,g,r

    output = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

    cv2.imwrite(args['dir']+"trial/"+"B3ack"+str(chosen),output)
